name: Super-Linter

on:
   push:
    branches:
      - test-1

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test code
        run: echo "hi"
